#DBMySql Config
spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/db_security
   username: dinhan
   password: dinhan
#Server Port Config
server:
  port: 9090
  servlet:
    context-path: /
#Google API Config
google:
  app:
    id: 834967421990-0kae1gt76uucci9eqrc3bent02605s15.apps.googleusercontent.com
    secret: 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
  link:
    get:
      token: https://accounts.google.com/o/oauth2/tokenNN
      user_info: https://www.googleapis.com/oauth2/v1/userinfo?access_token=
  redirect:
    uri: http://localhost:9090/loginwithgoogle
